spring.application.name=SERMS

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/serms_db
spring.datasource.username=root
spring.datasource.password=Imasha@200304

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080